### ISSUE TITLE
Issue in timezone when converting timestamp into persian datetime

### ISSUE THREAD

**Issue by bsobbe** [meysampg/intldate#2]
Hi,
When i'm trying to convert timestamp into persian dateTime, the date is absolutely right but the time has problem, the returned time has be in UTC timezone but it has about 4 hours difference from UTC (it's before that time), but when I set the default timezone into asia/tehran, it shows the UTC time, I think the returned time is not UTC and it's something else so that when I convert it into tehran timezone it changes to UTC, so how to change it to tehran timezone?, we've got a big problem

ps: I've tested it on 395/08/22 at about 3:20, It returned 8:20, When I changed it into asia/tehran it showed about 11:48 that still is not tehran time.

**Comment by meysampg** [comment]
I'll pursue code for this problem on next days and report results.

**Comment by meysampg** [comment]
Trait works correct for me! This is time in my OS:

![date_of_system](https://cloud.githubusercontent.com/assets/1416085/20382928/1fed4744-acc3-11e6-8dfd-d4249613486e.png)

and this is converted date with `Asia/Tehran` timezone using `IntlDate` trait:

![date_in_yii2](https://cloud.githubusercontent.com/assets/1416085/20382957/39fe6154-acc3-11e6-905d-2eda44ee4542.png)

Please make sure that  timezone of your OS is set and is for your region.
